# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('d', '草稿'), ('p', '发布')], default='d', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False, verbose_name='公司编号')),
                ('c_name', models.CharField(max_length=100, null=True, verbose_name='公司名称')),
                ('logo', models.ImageField(null=True, upload_to='', verbose_name='LOGO')),
                ('slogan', models.CharField(max_length=50, null=True, verbose_name='SLOGAN')),
                ('c_infor', models.CharField(max_length=1000, null=True, verbose_name='详细信息')),
                ('c_address', models.CharField(max_length=100, null=True, verbose_name='公司地址')),
                ('area', models.CharField(max_length=50, null=True, verbose_name='所属领域')),
                ('contacts', models.CharField(max_length=20, null=True, verbose_name='联系人')),
                ('cont_phone', models.CharField(max_length=20, null=True, verbose_name='联系人电话')),
                ('cont_mail', models.EmailField(max_length=254, null=True, verbose_name='联系人邮箱')),
                ('c_phone', models.CharField(max_length=20, null=True, verbose_name='公司电话')),
                ('c_email', models.EmailField(max_length=254, null=True, verbose_name='公司邮箱')),
                ('web', models.CharField(max_length=50, null=True, verbose_name='公司官网')),
                ('size', models.IntegerField(choices=[(0, '无信息'), (1, '10人以下'), (2, '10-50人'), (3, '50-100人'), (4, '100人以上')], default=0, verbose_name='公司规模')),
                ('develop', models.IntegerField(choices=[(0, '未融资'), (1, '天使轮'), (2, 'Pre_A轮'), (3, 'A轮'), (4, 'B轮'), (5, 'C轮'), (6, 'D轮及以上'), (7, '已上市')], default=0, verbose_name='发展阶段')),
                ('invest', models.CharField(max_length=100, null=True, verbose_name='投资机构')),
                ('identity', models.IntegerField(default=1, verbose_name='身份类型')),
                ('userid', models.IntegerField(default=0, null=True, verbose_name='用户编号')),
                ('comintroduce', models.CharField(max_length=10000, null=True, verbose_name='公司介绍')),
            ],
            options={
                'verbose_name_plural': '公司列表',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('f_position', models.CharField(max_length=20, null=True, verbose_name='现任职位')),
                ('f_photo', models.ImageField(null=True, upload_to='', verbose_name='照片')),
                ('f_blog', models.CharField(max_length=50, null=True, verbose_name='微博')),
                ('f_introduction', models.CharField(max_length=500, null=True, verbose_name='个人简介')),
                ('f_uid', models.IntegerField(default=1, verbose_name='身份编号')),
            ],
            options={
                'verbose_name_plural': '创始人',
                'db_table': 'founders',
            },
        ),
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('i_type', models.CharField(max_length=50, null=True, verbose_name='工作类型')),
                ('i_name', models.CharField(max_length=20, null=True, verbose_name='职位名称')),
                ('apart', models.CharField(max_length=50, null=True, verbose_name='所属部门')),
                ('infor_type', models.IntegerField(choices=[(0, '不限'), (1, '兼职'), (2, '实习')], default=0, verbose_name='工作性质')),
                ('i_payfor', models.CharField(max_length=20, null=True, verbose_name='月薪范围')),
                ('min_payfor', models.IntegerField(default=0, verbose_name='最低月薪')),
                ('max_payfor', models.IntegerField(default=0, verbose_name='最高月薪')),
                ('i_city', models.CharField(max_length=10, null=True, verbose_name='工作城市')),
                ('i_exp', models.CharField(max_length=100, null=True, verbose_name='要求工作经验')),
                ('min_exp', models.IntegerField(default=0, verbose_name='最低工作经验')),
                ('max_exp', models.IntegerField(default=0, verbose_name='最高工作经验')),
                ('i_degree', models.CharField(max_length=50, null=True, verbose_name='要求最低学历')),
                ('payshai', models.IntegerField(choices=[(0, '2k以下'), (1, '2k-5k'), (2, '5k-10k'), (3, '10k-15k'), (4, '15k-25k'), (5, '25k-50k'), (6, '50k以上')], default=0, verbose_name='薪资范围')),
                ('expshai', models.IntegerField(choices=[(0, '不限'), (1, '应届毕业生'), (2, '1年以下'), (3, '1-3年'), (4, '3-5年'), (5, '5-10年'), (6, '10年以上')], default=0, verbose_name='工作经验')),
                ('degreeshai', models.IntegerField(choices=[(0, '不限'), (1, '大专'), (2, '本科'), (3, '硕士'), (4, '博士')], default=0, verbose_name='学历')),
                ('areashai', models.IntegerField(choices=[(0, '全国'), (1, '北京'), (2, '上海'), (3, '广州'), (4, '深圳'), (5, '成都'), (6, '杭州'), (7, '武汉'), (8, '南京'), (9, '长春'), (10, '重庆'), (11, '长沙'), (12, '常州'), (13, '东莞'), (14, '大连'), (15, '佛山'), (16, '福州'), (17, '贵阳'), (18, '哈尔滨'), (19, '合肥'), (20, '海口'), (21, '惠州'), (22, '金华'), (23, '济南'), (24, '嘉兴'), (25, '昆明'), (26, '廊坊'), (27, '宁波'), (28, '南昌'), (29, '南宁'), (30, '南通'), (31, '青岛'), (32, '泉州'), (33, '石家庄'), (34, '绍兴'), (35, '沈阳'), (36, '苏州'), (37, '天津'), (38, ''), (39, '太原'), (40, '台州'), (41, '无锡'), (42, '温州'), (43, '西安'), (44, '厦门'), (45, '烟台'), (46, '珠海'), (47, ''), (48, '中山'), (49, '郑州')], default=0, verbose_name='工作地点')),
                ('i_wealth', models.CharField(max_length=20, null=True, verbose_name='职位诱惑')),
                ('i_address', models.CharField(max_length=200, null=True, verbose_name='详细工作地址')),
                ('i_introduce', models.CharField(max_length=500, null=True, verbose_name='职位描述介绍')),
                ('posttime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('company', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='App.Companies', verbose_name='发表公司')),
            ],
            options={
                'verbose_name_plural': '招聘信息',
                'db_table': 'information',
            },
        ),
        migrations.CreateModel(
            name='InfoStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '无状态'), (1, '已收藏'), (2, '订阅')], default=0)),
                ('information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Informations')),
            ],
            options={
                'verbose_name_plural': '职位选择状态表',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='PModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.ImageField(upload_to='upload/%Y/%m', verbose_name='photos')),
            ],
            options={
                'verbose_name_plural': '照片',
                'db_table': 'pic',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('s_pid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('pname', models.CharField(max_length=50, verbose_name='职位名称')),
                ('shang', models.IntegerField(default=1)),
                ('xia', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '工作职位',
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Positionstwo',
            fields=[
                ('t_pid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('pname', models.CharField(max_length=50, verbose_name='领域名称')),
                ('shang', models.IntegerField(default=1)),
                ('xia', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': '二级职位领域',
                'db_table': 'positionstwo',
            },
        ),
        migrations.CreateModel(
            name='Postionsone',
            fields=[
                ('o_pid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('pname', models.CharField(max_length=50, verbose_name='领域名称')),
                ('shang', models.IntegerField(default=0)),
                ('xia', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': '一级职业领域',
                'db_table': 'postionsone',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50, null=True, verbose_name='产品名称')),
                ('p_web', models.CharField(max_length=30, null=True, verbose_name='产品网址')),
                ('p_intr', models.CharField(max_length=500, null=True, verbose_name='产品介绍')),
                ('company', models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, to='App.Companies', verbose_name='所属公司')),
            ],
            options={
                'verbose_name_plural': '产品',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ResumeOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myjob', models.CharField(max_length=500, null=True, verbose_name='期望工作')),
                ('myexp', models.CharField(max_length=500, null=True, verbose_name='工作经验')),
                ('myobj', models.CharField(max_length=500, null=True, verbose_name='项目经验')),
                ('myedu', models.CharField(max_length=500, null=True, verbose_name='教育背景')),
                ('myinfor', models.CharField(max_length=500, null=True, verbose_name='自我描述')),
                ('display', models.CharField(max_length=500, null=True, verbose_name='作品展示')),
            ],
            options={
                'verbose_name_plural': '简历',
                'db_table': 'resume_ol',
            },
        ),
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.ImageField(null=True, upload_to='', verbose_name='简历文件')),
            ],
            options={
                'verbose_name_plural': '简历文件',
                'db_table': 'resumes',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=20)),
                ('c_id', models.ForeignKey(db_column='c_cid', on_delete=django.db.models.deletion.CASCADE, to='App.Companies')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='用户密码')),
                ('sex', models.BooleanField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('u_address', models.CharField(max_length=500, null=True, verbose_name='用户地址')),
                ('email', models.EmailField(max_length=254)),
                ('phonenum', models.CharField(max_length=11, null=True, verbose_name='手机号码')),
                ('degree', models.CharField(max_length=20, null=True, verbose_name='学历')),
                ('collage', models.CharField(max_length=50, null=True, verbose_name='毕业学校')),
                ('exper', models.IntegerField(choices=[(0, '没有经验'), (3, '1-3年'), (5, '3-5年'), (6, '五年以上')], default=0, verbose_name='工作经验')),
                ('u_job', models.CharField(max_length=50, null=True, verbose_name='意向工作')),
                ('u_regtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('identity', models.IntegerField(choices=[(0, '普通用户'), (1, '公司用户')], default=0, verbose_name='身份类型')),
            ],
            options={
                'verbose_name_plural': '用户列表',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='resumes',
            name='owner',
            field=models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='App.Users', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='resumeonline',
            name='owner',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to='App.Users', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='positionstwo',
            name='twoid',
            field=models.ForeignKey(db_column='o_pid', on_delete=django.db.models.deletion.CASCADE, to='App.Postionsone', verbose_name='所属领域'),
        ),
        migrations.AddField(
            model_name='positions',
            name='threeaid',
            field=models.ForeignKey(db_column='ta_pid', on_delete=django.db.models.deletion.CASCADE, to='App.Postionsone', verbose_name='所属领域1'),
        ),
        migrations.AddField(
            model_name='positions',
            name='threeid',
            field=models.ForeignKey(db_column='t_pid', on_delete=django.db.models.deletion.CASCADE, to='App.Positionstwo', verbose_name='所属领域2'),
        ),
        migrations.AddField(
            model_name='infostatus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Users'),
        ),
        migrations.AddField(
            model_name='informations',
            name='type',
            field=models.ForeignKey(db_column='s_pid', on_delete=django.db.models.deletion.CASCADE, to='App.Positions', verbose_name='职位类型'),
        ),
        migrations.AddField(
            model_name='companies',
            name='founder',
            field=models.ForeignKey(db_column='f_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Founders', verbose_name='创始人'),
        ),
    ]
