# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'getresumes',
            },
        ),
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name_plural': '[2]公司列表'},
        ),
        migrations.AlterModelOptions(
            name='positionstwo',
            options={'verbose_name_plural': '2二级职位领域'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '[3]公司产品'},
        ),
        migrations.AlterModelOptions(
            name='resumeonline',
            options={'verbose_name_plural': '在线简历'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': '[1]用户列表'},
        ),
        migrations.AddField(
            model_name='getresume',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Users', verbose_name='简历拥有着'),
        ),
        migrations.AddField(
            model_name='getresume',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.ResumeOnline', verbose_name='简历详情'),
        ),
    ]
